### ISSUE TITLE
Feature Request: Erkennen, ob „Mobile“ Switch aktiv

### ISSUE THREAD

**Issue by Jugibur** [contao-community-alliance/merger2#12]
Wäre es möglich, eine Abfrage zu integrieren, ob gerade das mobile Switch aktiv ist oder nicht? Damit könnte man sich u.U. auch ein ganzen mobiles Layout sparen.
Danke noch für diese tolle Erweiterung!

**Comment by dmolineus** [comment]
There will be an `isMobile` function in the next release which detects renders the page in the mobile view. If you only want to check if the mobile switch cookie is set, you might add true as parameter `isMobile(true)`. Otherwise the user agent might enable the mobile view as well if a mobile layout exist (same as Contao works).
